Rogii v1.2.8 dev
rogii-com/zlib pull request #1
Opened 2021-09-14 08:21 UTC by Shkarlatov

2021-09-14 09:57 UTC, chak3r commented on rogii/package.cmake
> +set_target_properties(
Actually, I can't remember why we don't need zLib on Linux for console application, but if you're doing CI for both, add the Linux section here. ( as a training;) )

2021-09-14 09:57 UTC, chak3r commented on rogii/version.cmake
> +set(
copypasted version from rapidjson, i guess

2021-09-14 09:57 UTC, chak3r commented on rogii/build_common.cmake
> +
Strange empty lines

2021-09-24 06:10 UTC, chak3r requested changes

2021-09-24 06:10 UTC, chak3r commented on CMakeLists.txt
> +    install(
need indentation

2021-09-24 06:10 UTC, chak3r commented on rogii/environment_linux.cmake
> +set(
REPOSITORY_OS is deprecated

2021-09-24 06:10 UTC, chak3r commented on rogii/package.cmake
> +set_target_properties(
no need to do

2021-09-24 11:11 UTC, chak3r approved these changes

2021-09-24 11:14 UTC, mr-bit approved these changes

2021-09-24 11:14 UTC, merged